### ISSUE TITLE
Bundler & rubygems should be tested on a docker based CI

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/bundler#6609]
I find the current CI overcomplicated and troubleshooting issues very hard.

* I find it weird and error prone that rubygems/bundler are tested on a system with `rvm` installed. In my opinion, they should be tested on top of bare ruby installations (no version managers, no rubygems or bundler other than what comes with `ruby`).

* Test failures are very hard to reproduce. If you run tests on a well known docker image, it's straighforward.

* Your CI environment is in your control. Right now, if TravisCI makes a bad change in the environment, it can break stuff and delay your work.

I feel this could speed up troubleshooting issues for contributors, for example, https://travis-ci.org/deivid-rodriguez/bundler/jobs/396655760, or https://github.com/bundler/bundler/pull/6502. It will also make the tools more bulletproof on docker environments, given the latest problems/regressions that have recently arised on docker environments (https://github.com/bundler/bundler/search?q=docker&type=Issues). Maybe the images we test against could become the official ruby images in the future :tada:

Any thoughts on this idea?

**Comment by indirect** [comment]
Well, if we are being scrupulously accurate, Bundler is currently tested on a Docker-based CI. Travis uses Docker images to create containers that the tests run inside.

It sounds like what you're asking for is something specific about how Ruby is set up within the container, either using the official Docker Ruby base image as our base, or creating a completely new Docker image from scratch ourselves in order to have full control over the CI environment.

One potential problem with that suggestion is (as far as I know) most Ruby installations in the world are still installed using RVM. If there is a problematic interaction between Bundler or RubyGems and RVM, which seems to happen every year or so, we wouldn't have any way to find out about it in advance unless our CI system also used RVM.

Can you describe more specifically what you're hoping to accomplish? For example, perhaps you want a docker-based environment for contributors, to make it easier to get started: https://github.com/duckinator/rgdev#readme. Perhaps you want an easy way to SSH in to a CI box to debug failures: https://docs.travis-ci.com/user/running-build-in-debug-mode/#Restarting-a-job-in-debug-mode-via-API.

Since our tests are in fact already running inside docker, perhaps you are asking about running our tests against a single specific docker image? That seems like something that would probably be worth doing, although I'm not sure if Travis provides support for us to choose our own base image. We might have to set up another CI system to do that.

**Comment by colby-swandale** [comment]
> I find it weird and error prone that rubygems/bundler are tested on a system with rvm installed. In my opinion, they should be tested on top of bare ruby installations (no version managers, no rubygems or bundler other than what comes with ruby).

rvm reflects a lot of people's production system, this lets us catch issues that would otherwise may not caught and fixed.

> Test failures are very hard to reproduce. If you run tests on a well known docker image, it's straighforward.

This is not always true, a lot of the hard issues to in the past that i've had to debug in Travis would also break the same way in docker.

> Your CI environment is in your control. Right now, if TravisCI makes a bad change in the environment, it can break stuff and delay your work.

It has in the past but the core team has worked with the TravisCI team to resolve the issues fairly quickly

**Comment by deivid-rodriguez** [comment]
> This is not always true, a lot of the hard issues to in the past that i've had to debug in Travis would also break the same way in docker.

The point is that if something breaks in docker, I can reproduce it. If something break in Travis, I'm in the dark. If you used, for example, the official ruby 2.1 image as a base for you ruby 2.1 tests, reproducing a build failure locally is as easy as downloading the docker image and running the spec inside it. In Travis, I have to install that version of ruby on my machine, install `rvm`, and hope the resulting local environment is similar to the one in Travis so that the failure reproduces.

Or maybe I can restart the job in debug mode and ssh into Travis as @indirect suggested. It might work, but it still feels inferior to being able to reproduce locally.

**Comment by deivid-rodriguez** [comment]
@indirect Hei! I'd like to apologize is my tone sounded too assertive or slightly agressive.

> Do you think there's a way we could add some sort of official-ruby-image testing to our CI?

I'll try to find an answer to this question that also shows the sort of solution I'm trying to achieve for CI in general :+1:

**Comment by esasse** [comment]
Looks like Travis now supports pulling images from Docker Hub? https://docs.travis-ci.com/user/docker/#using-a-docker-image-from-a-repository-in-a-build

And here we have Docker official images for ruby: https://hub.docker.com/_/ruby/

**Comment by colby-swandale** [comment]
can this be closed?

**Comment by deivid-rodriguez** [comment]
I haven't had that many problem reproducing issues locally lately, so I'm good with closing :+1:.
